version: "3"

services:
  origin-dapp:
    command:
      # Overwrite the dapp start command from docker-compose.yml to append
      # --bail so that an error code is generated if the build fails
      >
      /bin/bash -c "wait-for.sh -t 0 -q origin-messaging:9012 &&
      . set-ipfs-swarm.sh /app/ipfs/config &&
      wait-for.sh -t 0 -q origin:8080 --
      npm run start --prefix origin-dapp -- --bail"

  origin-tests:
    container_name: origin-tests
    image: origin
    environment:
      - DATABASE_URL=postgres://origin:origin@postgres/origin
    volumes:
      - ./origin-contracts/build:/app/origin-contracts/build
      - ./origin-tests/test:/app/origin-tests/test/
    command:
      >
      /bin/bash -c "wait-for.sh -t 0 -q event-listener:9499 --
      sleep 10 &&
      npm run test --prefix origin-tests"

